export {default as img1} from './img1.jpg'
export {default as img2} from './img2.jpg'
export {default as img3} from './img3.jpg'
export {default as img4} from './img4.jpg'
export {default as img5} from './img5.jpg'
export {default as img6} from './img6.jpg'
export {default as img7} from './img7jpg.jpg'
export {default as flyer2} from './flyer2.png'
export {default as left_leaf} from './hero-left-leaf.png'
export { default as right_leaf} from './hero-right-leaf.png' 
export {default as input2 } from './globe.mp4'
export {default as companyLogo} from './companyLogo2.png'
export {default as threeDtruct} from './3dApp.mp4'
export {default as threeDbike} from './3dbike.mp4'
export {default as img8} from './img10.jpg'
export {default as img9} from './peanutButter.jpg'
export {default as img10} from './restaurant.jpg'
export {default as img11} from './treynet.jpg'
export {default as img12} from './ddk.jpg'
export {default as img13} from './butcher.jpg'
export {default as img14} from './blueCorner.jpg'
export {default as img15} from './aidify.jpg'
export {default as img16} from './bootCamp.jpg'
export {default as img17} from './mcintoshi.jpg'
export {default as img18} from './locks.jpg'
export {default as cl1} from './blackCLjpg.jpg'



